# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9821068447d45f85bea52be73715eeb636a8eaf02922ffe08d0c587e3674a799a57d813b9bf74a71b88769bfbf1d27d167c1cc9644958ba78a90ab81e4435a05

test:
  secret_key_base: b40a302c951f494936f2874985abd0135225ab2634e2e8a214c84eceb36ebe24e829827b07509c55d825082d358f77d7b93359d9c39c25a64ba6147f3e142ec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
